spring:
  application:
    name: server-socket
  config:
    import: optional:configserver:http://config:8888

#server:
#  port: 1234
#
#spring:
#  application:
#    name: server-socket
  # data:
  #   mongodb:
  #     host: mongo
  #     port: 27017
  #     database: quiz
  #     username: lesser
  #     password: \!esser101Panda


#eureka:
#
#  instance:
#    instance-id: socket-service-${server.port}
#
#  client:
#    service-url:
#      defaultZone: http://discovery:8761/eureka